[providers]
node = "18"

[phases.setup]
nixPkgs = ["nodejs-18_x", "npm"]

[phases.install]
cmd = "npm install"

[phases.build]
cmds = [
  "npm ci",
  "npm run build"
]

[phases.start]
cmd = "npm run preview"

[variables]
NODE_ENV = "production"