/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
    "*.{js,ts,jsx,tsx,mdx}",
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        // Midnight Magnolia Brand Colors
        "midnight-blue": {
          DEFAULT: "#0A192F",
          50: "#E6EBF2",
          100: "#CCD7E5",
          200: "#99AFCB",
          300: "#6687B1",
          400: "#335F97",
          500: "#0A192F",
          600: "#081426",
          700: "#060F1C",
          800: "#040A13",
          900: "#020509",
        },
        "magnolia-white": {
          DEFAULT: "#FAF3E0",
          50: "#FFFFFF",
          100: "#FEFCF7",
          200: "#FAF3E0",
          300: "#F5E8C3",
          400: "#F0DDA6",
          500: "#EBD289",
          600: "#E6C76C",
          700: "#E1BC4F",
          800: "#DCB132",
          900: "#D7A615",
        },
        "sage-green": {
          DEFAULT: "#A3B18A",
          50: "#F4F6F1",
          100: "#E9EDE3",
          200: "#D3DBC7",
          300: "#BDC9AB",
          400: "#A7B78F",
          500: "#A3B18A",
          600: "#8FA076",
          700: "#7B8F62",
          800: "#677E4E",
          900: "#536D3A",
        },
        "warm-gray": {
          DEFAULT: "#D4B99F",
          50: "#F9F6F2",
          100: "#F3EDE5",
          200: "#E7DBCB",
          300: "#DBC9B1",
          400: "#CFB797",
          500: "#D4B99F",
          600: "#C8A585",
          700: "#BC916B",
          800: "#B07D51",
          900: "#A46937",
        },
        gold: {
          DEFAULT: "#D4AF37",
          50: "#F9F5E8",
          100: "#F3EBD1",
          200: "#E7D7A3",
          300: "#DBC375",
          400: "#CFAF47",
          500: "#D4AF37",
          600: "#B8962C",
          700: "#9C7D21",
          800: "#806416",
          900: "#644B0B",
        },
      },
      fontFamily: {
        playfair: ["var(--font-playfair)", "serif"],
        lora: ["var(--font-lora)", "serif"],
        montserrat: ["var(--font-montserrat)", "sans-serif"],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
      boxShadow: {
        mystical: "0 10px 25px -3px rgba(163, 177, 138, 0.1), 0 4px 6px -2px rgba(163, 177, 138, 0.05)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
